-- 名簿データのテーブル
CREATE TABLE IF NOT EXISTS public.directory_employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb
);

-- 列設定のテーブル
CREATE TABLE IF NOT EXISTS public.directory_columns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT UNIQUE NOT NULL,
    label TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'text',
    "order" INTEGER NOT NULL,
    is_visible BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- リアルタイム同期の有効化 (存在確認付き)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'directory_employees') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE directory_employees;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'directory_columns') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE directory_columns;
  END IF;
END $$;

-- RLS (Row Level Security) の設定
ALTER TABLE public.directory_employees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all" ON public.directory_employees;
CREATE POLICY "Allow all" ON public.directory_employees FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.directory_columns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all" ON public.directory_columns;
CREATE POLICY "Allow all" ON public.directory_columns FOR ALL USING (true) WITH CHECK (true);

-- チームデータのテーブル
CREATE TABLE IF NOT EXISTS public.teams (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- 既存テーブルへのカラム追加（マイグレーション）
ALTER TABLE public.teams ADD COLUMN IF NOT EXISTS icon TEXT;

-- メッセージ/タスクデータのテーブル
CREATE TABLE IF NOT EXISTS public.messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    team_id UUID REFERENCES public.teams(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id), -- 認証済みユーザーと紐付け
    content TEXT NOT NULL,
    status TEXT DEFAULT 'todo', -- todo, done, pending
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- 既存テーブルへのカラム追加（マイグレーション）
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'todo';
ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);

-- リアルタイム同期の有効化 (Teams/Messages)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'teams') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE teams;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'messages') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
  END IF;
END $$;

-- RLS設定
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all teams" ON public.teams;
CREATE POLICY "Allow all teams" ON public.teams FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow all messages" ON public.messages;
CREATE POLICY "Allow all messages" ON public.messages FOR ALL USING (true) WITH CHECK (true);

-- 初期データ投入 (Teams)
INSERT INTO public.teams (name, icon) VALUES 
('Team Alpha', '🚀'),
('Team Beta', '⚡'),
('Genaral', '🏢')
ON CONFLICT DO NOTHING;
